# Generated by Django 5.2.3 on 2025-06-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coformacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coformacion',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='EstadoProceso',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_proceso',
            },
        ),
        migrations.CreateModel(
            name='EstadosCartera',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estados_cartera',
            },
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('facultad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'facultades',
            },
        ),
        migrations.CreateModel(
            name='MateriasNucleo',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'materias_nucleo',
            },
        ),
        migrations.CreateModel(
            name='NivelesIngles',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'niveles_ingles',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('permiso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='PlantillasCorreo',
            fields=[
                ('plantilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plantillas_correo',
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SectoresEconomicos',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sectores_economicos',
            },
        ),
        migrations.CreateModel(
            name='TamanosEmpresa',
            fields=[
                ('tamano_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tamanos_empresa',
            },
        ),
        migrations.CreateModel(
            name='TiposActividad',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_actividad',
            },
        ),
        migrations.CreateModel(
            name='TiposContacto',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_contacto',
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('tipo_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('formato_url', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='ContactosEmpresa',
            fields=[
                ('contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='coformacion.empresas')),
            ],
            options={
                'db_table': 'contactos_empresa',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('email_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('semestre', models.IntegerField()),
                ('jornada', models.CharField(choices=[('Diurna', 'Diurna'), ('Nocturna', 'Nocturna'), ('Mixta', 'Mixta')], max_length=8)),
                ('promedio_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Graduado', 'Graduado'), ('Retirado', 'Retirado')], default='Activo', max_length=9)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_id', models.ForeignKey(blank=True, db_column='empresa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.empresas')),
                ('estado_cartera_id', models.ForeignKey(blank=True, db_column='estado_cartera_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.estadoscartera')),
                ('nivel_ingles_id', models.ForeignKey(blank=True, db_column='nivel_ingles_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.nivelesingles')),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='ObjetivosAprendizaje',
            fields=[
                ('objetivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coformacion.materiasnucleo')),
            ],
            options={
                'db_table': 'objetivos_aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='OfertasEmpresas',
            fields=[
                ('oferta_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.empresas')),
            ],
            options={
                'db_table': 'ofertasempresas',
            },
        ),
        migrations.CreateModel(
            name='HistorialComunicaciones',
            fields=[
                ('comunicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.estudiantes')),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.plantillascorreo')),
            ],
            options={
                'db_table': 'historial_comunicaciones',
            },
        ),
        migrations.CreateModel(
            name='ProcesoCoformacion',
            fields=[
                ('proceso_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.empresas')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.estadoproceso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.estudiantes')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.ofertasempresas')),
            ],
            options={
                'db_table': 'proceso_coformacion',
            },
        ),
        migrations.CreateModel(
            name='DocumentosProceso',
            fields=[
                ('documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_proceso/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.procesocoformacion')),
            ],
            options={
                'db_table': 'documentos_proceso',
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('duracion_semestres', models.IntegerField()),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Híbrido', 'Híbrido')], max_length=10)),
                ('nivel', models.CharField(choices=[('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Profesional', 'Profesional'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría')], max_length=15)),
                ('resolucion_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('facultad_id', models.ForeignKey(db_column='facultad_id', on_delete=django.db.models.deletion.RESTRICT, to='coformacion.facultades')),
            ],
            options={
                'db_table': 'programas',
            },
        ),
        migrations.AddField(
            model_name='materiasnucleo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coformacion.programas'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='programa_id',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.RESTRICT, to='coformacion.programas'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='promocion_id',
            field=models.ForeignKey(blank=True, db_column='promocion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.promociones'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.sectoreseconomicos'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tamano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.tamanosempresa'),
        ),
        migrations.CreateModel(
            name='CalendarioActividades',
            fields=[
                ('actividad_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coformacion.procesocoformacion')),
                ('tipo_actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coformacion.tiposactividad')),
            ],
            options={
                'db_table': 'calendario_actividades',
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coformacion.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coformacion.roles')),
            ],
            options={
                'db_table': 'roles_permisos',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
