# Generated by Django 5.2.3 on 2025-06-16 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coformacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='actividad_economica',
            field=models.TextField(default='Tecnologia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='ciudad',
            field=models.CharField(default='Bogota', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='convenio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='cuota_sena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='departamento',
            field=models.CharField(default='Bogota', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='direccion',
            field=models.CharField(default='calle 50', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='estado_convenio',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('No Vigente', 'No Vigente'), ('En Trámite', 'En Trámite')], default='En Trámite', max_length=20),
        ),
        migrations.AddField(
            model_name='empresas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='fecha_convenio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='horario_laboral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='numero_empleados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='razon_social',
            field=models.CharField(default='richarsas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='trabaja_sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='sector',
            field=models.ForeignKey(db_column='sector_id', default=2, on_delete=django.db.models.deletion.RESTRICT, to='coformacion.sectoreseconomicos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tamano',
            field=models.ForeignKey(db_column='tamano_id', default=2, on_delete=django.db.models.deletion.RESTRICT, to='coformacion.tamanosempresa'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['sector', 'estado_convenio'], name='idx_empresa_sector'),
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['estado_convenio', 'estado'], name='idx_empresa_estado'),
        ),
    ]
