# Generated by Django 5.2.3 on 2025-06-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coformacion', '0003_update_ofertas_empresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasempresas',
            name='apoyo_economico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ofertasempresas',
            name='empresa',
            field=models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='coformacion.empresas'),
        ),
    ]
